version: "3"
services:
  gibbon:
    build: ./Gibbon
    ## Prefer building with above line, but comment it and uncomment the next line if you need to avoid building (doing so will cause redundant gibbon download in container)
    # image: kerrongordon/gibbon:26.0.00 
    container_name: gibbon
    restart: unless-stopped
    ports:
      - 8480:80
    volumes:
      - ./_Volumes/gibbonEd:/var/www/gibbon.local/
      - ./NepaliIntegration_GibbonFiles/NepaliIntegration:/var/www/gibbon.local/NepaliIntegration
      - ./NepaliIntegration_GibbonFiles/modules/Timetable/moduleFunctions.php:/var/www/gibbon.local/modules/Timetable/moduleFunctions.php
      - ./NepaliIntegration_GibbonFiles/index_custom.php:/var/www/gibbon.local/index_custom.php
      - ./NepaliIntegration_GibbonFiles/index.php:/var/www/gibbon.local/index.php
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # ports:
    #   - 3406:3306
    volumes:
      - ./_Volumes/gibbon_db:/var/lib/mysql